server:
  port: 9090

spring:
  datasource:
    driveClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tour
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true